name: Build ZMK roBa (XIAO BLE)
on:
  push:
  workflow_dispatch:

jobs:
  build_left:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      board: seeeduino_xiao_ble
      shield: roBa_L

  build_right:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      board: seeeduino_xiao_ble
      shield: roBa_R
